/**
 * Created by Bkz on 2018/5/17.
 */
let imgAll = {};
imgAll.home = [
    "static/seven/active_bg.jpg",
    "static/seven/go.png",
    "static/seven/active_alert.png",
    /*select*/
    "static/seven/select_bg.jpg",
    "static/seven/logo.png",
    "static/seven/black_01.png",
    "static/seven/black_02.png",
    "static/seven/black_03.png",
    "static/seven/hover_01.png",
    "static/seven/hover_02.png",
    "static/seven/hover_03.png",
    "static/seven/start_play.png",
    "static/seven/click.png",
    "static/seven/lift.png",
    "static/seven/finger.gif",
    /*play*/

    // "static/play/0.png",
    // "static/play/1.png",
    // "static/play/2.png",
    // "static/play/3.png",
    // "static/play/4.png",
    // "static/play/5.png",
    // "static/play/6.png",
    // "static/play/7.png",
    // "static/play/8.png",
    // "static/play/9.png",
    // "static/play/bar_01.png",
    // "static/play/bar_02.png",
    // "static/play/bar_03.png",
    // "static/play/bar_01_gift.png",
    // "static/play/bar_02_gift.png",
    // "static/play/bar_03_gift.png",
    // "static/play/cricle_01.png",
    // "static/play/cricle_02.png",
    // "static/play/cricle_03.png",
    // "static/play/get_btn.png",
    // "static/play/miss.png",
    // "static/play/nice.png",
    // "static/play/ncs_info.png",
    // "static/play/play_bg.jpg",
    // "static/play/play_bg_01.png",
    // "static/play/play_bg_02.png",
    // "static/play/play_bg_03.png",
    // "static/play/top_bg.png",

    //result
    "static/play/play_bg.jpg",
    "static/result/0.png",
    "static/result/1.png",
    "static/result/2.png",
    "static/result/3.png",
    "static/result/4.png",
    "static/result/5.png",
    "static/result/6.png",
    "static/result/7.png",
    "static/result/8.png",
    "static/result/9.png",
    "static/result/again.png",
    "static/result/find.png",
    "static/result/give_rewards.png",
    "static/result/play_pao.png",
    "static/result/rank_list.png",
    "static/result/result_bar.png",
    "static/result/top_info.png",

    "static/result/play_people1.png",
    "static/result/play_people2.png",
    "static/result/play_people3.png",
    "static/result/product1_1.png",
    "static/result/product1_2.png",
    "static/result/product1_3.png",
    "static/result/product2_1.png",
    "static/result/product2_2.png",
    "static/result/product2_3.png",
    "static/result/product3_1.png",
    "static/result/product3_2.png",
    "static/result/product3_3.png",


];

module.exports = imgAll;
